services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: cybernop/yamr-app:latest
    ports:
      - 8085:80
    restart: unless-stopped

  service:
    build:
      context: .
      dockerfile: Dockerfile.service
    image: cybernop/yamr-service:latest
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: cybernop/yamr-db:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
