@host = localhost:8080

###

# @name kinds
GET http://{{host}}/kinds

###

@kind = {{kinds.response.body.kinds[0].id}}

GET http://{{host}}/readings?kind={{kind}}

###

POST http://{{host}}/reading
Content-Type: application/json

{
    "kind_id": 1,
    "recordedOn": "2024-01-01T00:00:00Z",
    "reading": 98798
}
